# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-21 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csdp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionGraphEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_i', models.BigIntegerField()),
                ('node_j', models.BigIntegerField()),
                ('weight', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdp.Session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionGraphNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.BigIntegerField()),
                ('node_type', models.CharField(max_length=1)),
                ('activity', models.CharField(max_length=50, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdp.Session')),
            ],
        ),
    ]
