# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-19 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0002_sessionplan_sessionplandetail_sessionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionuser',
            name='vehicle',
            field=models.SmallIntegerField(null=True),
        ),
    ]
