# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-20 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rs', '0005_auto_20181019_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
