# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-18 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('city', models.CharField(choices=[('MEL', 'Melbourne'), ('MHK', 'Manhattan'), ('UIO', 'Quito')], max_length=20)),
                ('current', models.BooleanField()),
            ],
        ),
    ]
