# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-18 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_cost', models.FloatField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs.Session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionPlanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_i', models.BigIntegerField()),
                ('edge_j', models.BigIntegerField()),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs.SessionPlan')),
            ],
        ),
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.BooleanField()),
                ('origin', models.BigIntegerField()),
                ('destination', models.BigIntegerField()),
                ('activity', models.CharField(choices=[('amenity:post_office', 'post office'), ('shop:mall', 'shop mall'), ('amenity:restaurant', 'restaurant'), ('shop:supermarket', 'supermarket'), ('shop:convenience', 'convenience'), ('leisure:swimming_pool', 'swimming pool'), ('amenity:bar', 'bar'), ('amenity:fast_food', 'fast food'), ('amenity:cafe', 'cafe'), ('leisure:fitness_centre', 'fitness centre'), ('amenity:pub', 'pub')], max_length=50)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs.Session')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
