# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-19 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0003_sessionuser_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='number_users',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
