# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-22 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0006_session_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='current',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='sessionuser',
            name='creator',
        ),
        migrations.AlterField(
            model_name='sessionuser',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rs.Session'),
        ),
    ]
