# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-22 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0007_auto_20181023_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionuser',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs.Session'),
        ),
        migrations.AlterField(
            model_name='sessionuser',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
