# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-23 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0009_sessiongraph_sessiongraphhotspot_sessiongraphpoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiongraph',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessiongraphpoi',
            name='activity',
            field=models.CharField(default='A', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionuser',
            name='destination',
            field=models.BigIntegerField(null=True),
        ),
    ]
