# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-23 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0011_auto_20181023_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionuser',
            name='destination',
            field=models.BigIntegerField(null=True),
        ),
    ]
