# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-23 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0012_auto_20181023_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiongraph',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='sessiongraphhotspot',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='sessiongraphpoi',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='sessionplan',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='sessionplandetail',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='sessionuser',
            old_name='session_id',
            new_name='session',
        ),
    ]
