# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-24 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0014_auto_20181023_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionGraphNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.BigIntegerField()),
                ('node_type', models.CharField(max_length=1)),
                ('activity', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='SessionGraph',
            new_name='SessionGraphEdge',
        ),
        migrations.AddField(
            model_name='session',
            name='centroid_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='centroid_lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessiongraphnode',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs.Session'),
        ),
    ]
