# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-24 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0015_auto_20181024_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiongraphhotspot',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sessiongraphpoi',
            name='session',
        ),
        migrations.DeleteModel(
            name='SessionGraphHotspot',
        ),
        migrations.DeleteModel(
            name='SessionGraphPoi',
        ),
    ]
