# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-24 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0016_auto_20181024_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiongraphedge',
            old_name='edge_i',
            new_name='node_i',
        ),
        migrations.RenameField(
            model_name='sessiongraphedge',
            old_name='edge_j',
            new_name='node_j',
        ),
    ]
