# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-25 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0019_auto_20181025_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionuser',
            name='activity',
            field=models.CharField(choices=[('amenity:post_office', 'post office'), ('shop:mall', 'shop mall'), ('amenity:restaurant', 'restaurant'), ('shop:supermarket', 'supermarket'), ('shop:convenience', 'convenience'), ('leisure:swimming_pool', 'swimming pool'), ('amenity:bar', 'bar'), ('amenity:fast_food', 'fast food'), ('amenity:cafe', 'cafe'), ('leisure:fitness_centre', 'fitness centre'), ('amenity:pub', 'pub')], max_length=50, null=True),
        ),
    ]
