# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-25 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0020_auto_20181026_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionuser',
            name='ready_to_travel',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
