# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-25 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0021_sessionuser_ready_to_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionuser',
            name='ready_to_travel',
            field=models.BooleanField(default=False),
        ),
    ]
