# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-26 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0022_auto_20181026_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
