# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-29 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0023_auto_20181026_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='travel_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='activity',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionplan',
            name='travel_cost',
            field=models.FloatField(null=True),
        ),
    ]
