# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-31 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0024_auto_20181029_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPlanVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs.SessionPlan')),
            ],
        ),
        migrations.CreateModel(
            name='SessionPlanVehiclePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_i', models.BigIntegerField()),
                ('node_j', models.BigIntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs.SessionPlanVehicle')),
            ],
        ),
        migrations.CreateModel(
            name='SessionUserVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='sessionuser',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='sessionuservehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs.SessionUser'),
        ),
        migrations.AddField(
            model_name='sessionuservehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs.SessionPlanVehicle'),
        ),
    ]
