# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-31 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0025_auto_20181031_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionPlanVehiclePlan',
            new_name='SessionPlanVehicleRoute',
        ),
    ]
