# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-31 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0026_auto_20181031_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionplandetail',
            name='plan',
        ),
        migrations.DeleteModel(
            name='SessionPlanDetail',
        ),
    ]
